apiVersion: v1
kind: Pod
metadata:
   name: fib-client-pod
   labels:
      app: client
      type: frontend

spec:
  containers:
     - name: client-container
       image: gopidoc77/fib-client:latest
